### ISSUE TITLE
Contribution to RESTGo project 

### ISSUE THREAD

**Issue by kkennethho** [codingsoo/REST_Go#10]
Hi, @sumleo and I would like to contribute to the RESTGo project with the following:
1. Documentation for how to create a docker image to run the RESTful services locally and how to configure it (similar to https://hub.docker.com/r/swaggerapi/petstore)

2. A fully automated testing framework for RESTful APIs. Its key features are:
- ChatGPT Enabled Instance Generation, Sequence Generation. 
- Reinforcement Learning Enabled Instance Generation

Thank you!

**Comment by codingsoo** [comment]
Hi @kkennethho and @sumleo,

Thank you for your interest in this project! You are always welcome to add more services and testing tools along with documentation. Please send us a pull request to contribute! Thank you.
