### ISSUE TITLE
Setup.sh doesnt work

### ISSUE THREAD

**Issue by eduardoportella** [codingsoo/REST_Go#12]
i runnit setup.sh at first but he returns me an error that he couldnt find ./venv/bin/activate
the commands are kind confusing for me (im a noob), and i would like a help plss.
i run the command for python 3, but my get_cov.sh get a connection refused.

**Comment by eduardoportella** [comment]
output setup.sh:
![Captura de tela de 2024-06-04 21-34-15](https://github.com/codingsoo/REST_Go/assets/62074034/8d8a17fc-a27f-4a8f-b8ae-77b10d4e6dbc)

**Comment by codingsoo** [comment]
Hi [eduardoportella](https://github.com/eduardoportella), I am sorry for the late response. The message says you need the venv directory. You can have the venv directory using this command `python3 -m venv venv`. Please reopen this issue if you still have the issue!
