### ISSUE TITLE
Unable to generate coverage reports

### ISSUE THREAD

**Issue by akshathsk** [codingsoo/REST_Go#6]
I tried running EvoMasterBB on projects genome-nexus and market. The tool executed successfully but I am unable to generate reports.

Commands executed - 
```
sh setup.sh
python3 run_tool.py EvoMasterBB market 10206
```

Output (success) -

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/42092528/231777310-e6c6477f-ef6c-455a-8314-6df332a700fa.png">

```
python3 report.py 10206 market
```

Output (failed) -

<img width="306" alt="image" src="https://user-images.githubusercontent.com/42092528/231777505-0e59fe1a-a1fb-4dfd-aaa8-6566351e5fba.png">

It is unable to find the jacoco generated files - 

```
mv: cannot stat '*.csv': No such file or directory
mv: cannot stat 'error.json': No such file or directory
mv: cannot stat 'time.json': No such file or directory
mv: cannot stat 'jacoco*.exec': No such file or directory
```

Similar error with the other project genome-nexus as well.

**Comment by codingsoo** [comment]
Hi, I think some dependencies are missing. Can you also share the output of the command `sh setup.sh`?

**Comment by codingsoo** [comment]
I've updated the generating report steps. Please open this issue again if you still have the problem!
