### ISSUE TITLE
FileNotFoundError while running some API Testing Tools

### ISSUE THREAD

**Issue by Suraj-Vashista-BK** [codingsoo/REST_Go#7]
I tried running EvoMasterBB on the `cwa-verification` project and encountered the below error - 

```
FileNotFoundError: [Errno 2] No such file or directory: ‘./services/jdk11/cwa-verification/em/embedded/rest/cwa-verification/cp.txt’
```

output:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/43924312/231853132-2bd9d232-7ccd-423f-8396-7c4333326b36.png">

Similar errors were seen in - 
1. `features-service` and `languagetool` while running `EvoMaster BB`
2. `cwa-verification` while running `RestTest`

**Comment by codingsoo** [comment]
Hi, I think you missed the maven dependency building step. setup script involves the step. Can you give me the output of `sh setup.sh` command?

**Comment by codingsoo** [comment]
This error occurs when you did not run "mvn dependency:build-classpath -Dmdep.outputFile=cp.txt." Please run it before using the benchmark!
