### ISSUE TITLE
OCVN startup failed

### ISSUE THREAD

**Issue by LALAYANG** [codingsoo/REST_Go#9]
Hi, 

When running service `ocvn`, it failed to start up with excetions of `Unable to start embedded Tomcat`, please see the following details, I’d appreciate it if you could provide any guidance!

1) Commands to reproduce the failure:
```
python3 run_service.py ocvn [port] blackbox 
```

2) Exceptions
[`em.embedded.org.devgateway.ocvn.RunServer` ](https://github.com/codingsoo/REST_Go/blob/master/services/evo_jdk8/em/embedded/rest/ocvn/src/main/java/em/embedded/org/devgateway/ocvn/RunServer.java)failed with exceptions:
```
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat
```
- please see details of the output in [log_file](https://github.com/LALAYANG/share_repo/blob/main/ocvn_blackbox_RunServer.log), lines starting from 202;
- the shell commands generated to run this service can be found [here](https://github.com/LALAYANG/share_repo/blob/main/run.sh).

I tried to update JVM options with `--add-opens java.base/java.lang.invoke=ALL-UNNAMED` (based on line 459 of the log); or make changes of dependencies such as`spring-boot-starter-tomcat`, `spring-boot-starter-web`, etc., to avoid dependency conflicts, but didn’t fix it successfully. 

Thanks again for your help!

**Comment by codingsoo** [comment]
Hi, I am sorry for the late response. It seems like you have an issue with running the container. I had the same issue when I use different OS environment. You need to use appropriate Docker image for your environment. For example, if you are using MacOS, please replace the `mongo:3.2` with `arm64v8/mongo:3.4` in the [RunServer.java](https://github.com/codingsoo/REST_Go/blob/master/services/evo_jdk8/em/embedded/rest/ocvn/src/main/java/em/embedded/org/devgateway/ocvn/RunServer.java) file.
